input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Ensure we always have a service name field for easy filtering.
  if ![service] and [springAppName] {
    mutate { add_field => { "service" => "%{[springAppName]}" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
